const counties = [
    {value:'Afghanistan',label:'Afghanistan'},
    {value:'Albania',label:'Albania'},
    {value:'Algeria',label:'Algeria'},
    {value:'Andorra',label:''},
    {value:'Angola',label:''},
    {value:'Antigua and Barbuda',label:''},
    {value:'Argentina',label:''},
    {value:'Armenia',label:''},
    {value:'Australia',label:''},
    {value:'Austria',label:''},
    {value:'Azerbaijan',label:''},
    {value:'Bahamas',label:''},
    {value:'Bahrain',label:''},
    {value:'Bangladesh',label:''},
    {value:'Barbados',label:''},
    {value:'Belarus',label:''},
    {value:'Belgium',label:''},
    {value:'Belize',label:''},
    {value:'Benin',label:''},
    {value:'Bhutan',label:''},
    {value:'Bolivia (Plurinational State of)',label:''},
    {value:'Bosnia and Herzegovina',label:''},
    {value:'Botswana',label:''},
    {value:'Brazil',label:''},
    {value:'Brunei Darussalam',label:''},
    {value:'Bulgaria',label:''},
    {value:'Burkina Faso',label:''},
    {value:'Burundi',label:''},
    {value:'Cabo Verde',label:''},
    {value:'Cambodia',label:''},
    {value:'Cameroon',label:''},
    {value:'Canada',label:''},
    {value:'Central African Republic (the)',label:''},
    {value:'Chad',label:''},
    {value:'Chile',label:''},
    {value:'China',label:''},
    {value:'Colombia',label:''},
    {value:'Comoros (the)',label:''},
    {value:'Congo (the)',label:''},
    {value:'Costa Rica',label:''},
    {value:'Côte dIvoire',label:''},
    {value:'Croatia',label:''},
    {value:'Cuba',label:''},
    {value:'Cyprus',label:''},
    {value:'Czechia',label:''},
    {value:'Democratic People Republic of Korea (the)',label:''},
    {value:'Democratic Republic of the Congo (the)',label:''},
    {value:'Denmark',label:''},
    {value:'Djibouti',label:''},
    {value:'Dominica',label:''},
    {value:'Dominican Republic (the)',label:''},
    {value:'Ecuador',label:''},
    {value:'Egypt',label:''},
    {value:'El Salvador',label:''},
    {value:'Equatorial Guinea',label:''},
    {value:'Eritrea',label:''},
    {value:'Estonia',label:''},
    {value:'Eswatini',label:''},
    {value:'Ethiopia',label:''},
    {value:'Fiji',label:''},
    {value:'Finland',label:''},
    {value:'France',label:''},
    {value:'Gabon',label:''},
    {value:'Gambia (the)',label:''},
    {value:'Georgia',label:''},
    {value:'Germany',label:''},
    {value:'Ghana',label:''},
    {value:'Greece',label:''},
    {value:'Grenada',label:''},
    {value:'Guatemala',label:''},
    {value:'Guinea',label:''},
    {value:'Guinea-Bissau',label:''},
    {value:'Guyana',label:''},
    {value:'Haiti',label:''},
    {value:'Honduras',label:''},
    {value:'Hungary',label:''},
    {value:'Iceland',label:''},
    {value:'India',label:''},
    {value:'Indonesia',label:''},
    {value:'Iran (Islamic Republic of)',label:''},
    {value:'Iraq',label:''},
    {value:'Ireland',label:''},
    {value:'Israel',label:''},
    {value:'Italy',label:''},
    {value:'Jamaica',label:''},
    {value:'Japan',label:''},
    {value:'Jordan',label:''},
    {value:'Kazakhstan',label:''},
    {value:'Kenya',label:''},
    {value:'Kiribati',label:''},
    {value:'Kuwait',label:''},
    {value:'Kyrgyzstan',label:''},
    {value:'Lao People Democratic Republic (the)',label:''},
    {value:'Latvia',label:''},
    {value:'Lebanon',label:''},
    {value:'Lesotho',label:''},
    {value:'Liberia',label:''},
    {value:'Libya',label:''},
    {value:'Liechtenstein',label:''},
    {value:'Lithuania',label:''},
    {value:'Luxembourg',label:''},
    {value:'Madagascar',label:''},
    {value:'Malawi',label:''},
    {value:'Malaysia',label:''},
    {value:'Maldives',label:''},
    {value:'Mali',label:''},
    {value:'Malta',label:''},
    {value:'Marshall Islands (the)',label:''},
    {value:'Mauritania',label:''},
    {value:'Mauritius',label:''},
    {value:'Mexico',label:''},
    {value:'Micronesia (Federated States of)',label:''},
    {value:'Monaco',label:''},
    {value:'Mongolia',label:''},
    {value:'Montenegro',label:''},
    {value:'Morocco',label:''},
    {value:'Mozambique',label:''},
    {value:'Myanmar',label:''},
    {value:'Namibia',label:''},
    {value:'Nauru',label:''},
    {value:'Nepal',label:''},
    {value:'Netherlands (the)',label:''},
    {value:'New Zealand',label:''},
    {value:'Nicaragua',label:''},
    {value:'Niger (the)',label:''},
    {value:'Nigeria',label:''},
    {value:'North Macedonia',label:''},
    {value:'Norway',label:''},
    {value:'Oman',label:''},
    {value:'Pakistan',label:''},
    {value:'Palau',label:''},
    {value:'Panama',label:''},
    {value:'Papua New Guinea',label:''},
    {value:'Paraguay',label:''},
    {value:'Peru',label:''},
    {value:'Philippines (the)',label:''},
    {value:'Poland',label:''},
    {value:'Portugal',label:''},
    {value:'Qatar',label:''},
    {value:'Republic of Korea (the)',label:''},
    {value:'Republic of Moldova (the)',label:''},
    {value:'Romania',label:''},
    {value:'Russian Federation (the)',label:''},
    {value:'Rwanda',label:''},
    {value:'Saint Kitts and Nevis',label:''},
    {value:'Saint Lucia',label:''},
    {value:'Saint Vincent and the Grenadines',label:''},
    {value:'Samoa',label:''},
    {value:'San Marino',label:''},
    {value:'Sao Tome and Principe',label:''},
    {value:'Saudi Arabia',label:''},
    {value:'Senegal',label:''},
    {value:'Serbia',label:''},
    {value:'Seychelles',label:''},
    {value:'Sierra Leone',label:''},
    {value:'Singapore',label:''},
    {value:'Slovakia',label:''},
    {value:'Slovenia',label:''},
    {value:'Solomon Islands',label:''},
    {value:'Somalia',label:''},
    {value:'South Africa',label:''},
    {value:'South Sudan',label:''},
    {value:'Spain',label:''},
    {value:'Sri Lanka',label:''},
    {value:'Sudan (the)',label:''},
    {value:'Suriname',label:''},
    {value:'Sweden',label:''},
    {value:'Switzerland',label:''},
    {value:'Syrian Arab Republic (the)',label:''},
    {value:'Tajikistan',label:''},
    {value:'Thailand',label:''},
    {value:'Timor-Leste',label:''},
    {value:'Togo',label:''},
    {value:'Tonga',label:''},
    {value:'Trinidad and Tobago',label:''},
    {value:'Tunisia',label:''},
    {value:'Türkiye',label:''},
    {value:'Turkmenistan',label:''},
    {value:'Tuvalu',label:''},
    {value:'Uganda',label:''},
    {value:'Ukraine',label:''},
    {value:'United Arab Emirates (the)',label:''},
    {value:'United Kingdom of Great Britain and Northern Ireland (the)',label:''},
    {value:'United Republic of Tanzania (the)',label:''},
    {value:'United States of America (the)',label:''},
    {value:'Uruguay',label:''},
    {value:'Uzbekistan',label:''},
    {value:'Vanuatu',label:''},
    {value:'Venezuela (Bolivarian Republic of)',label:''},
    {value:'Viet Nam',label:''},
    {value:'Yemen',label:''},
    {value:'Zambia',label:''},
    {value:'Zimbabwe',label:''},
]